version: '3.9'

services:
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - '8000:8000'
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      PORT:

  database:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
