version: '3.9'

services:
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - '8000:8000'
    healthcheck:
      test: curl http://localhost:8000/health
      interval: 3s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      PORT:
    networks:
      - backend

  database:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    networks:
     - backend

  # frontend:
  #   build:
  #     dockerfile: Dockerfile
  #     context:  ./frontend/chat-app-frontend
  #   command: ["npm", "start"]
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - backend

networks:
  backend:
